# Generated by Django 5.1.2 on 2025-11-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentNew',
            new_name='Student',
        ),
    ]
