# Generated by Django 5.1.2 on 2025-11-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_rename_studentnew_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentNew',
        ),
    ]
